### ISSUE TITLE
I used to use cssfmt, and just updated to stylefmt, but I'm having trouble getting it to work.

### ISSUE THREAD

**Issue by krompus** [kewah/vim-stylefmt#5]
I followed the instructions; cleaned my plugins and installed this one.

When I try the commands (which are recognised; they autocomplete), I get this:

    Error while executing stylefmt! no changes made.
    zsh:1: command not found: stylefmt

I recently switched to `zsh`, and I'm still getting settled in. I'm not sure if the zsh part in the error means it's a problem with zsh. I noticed that `stylefmt` has a lowercase `s` in the error report, despite writing `Stylefmt` when calling the command.

Any ideas?

**Comment by kewah** [comment]
Hej,

Sorry I don't know why your command is converted to lowercase. I also use zsh and tried using vim & neovim and both work as expected (by running the command `:Stylefmt`). 
Did you try to map the command to see if you get the same behaviour? (I personally map it on [`<leader>cs`](https://github.com/kewah/dotfiles/blob/e561994cf97b0738b0b0fe16e40672bb789dfe8d/vim/config/plugins.vim#L237)).

Do you get the same behaviour with another command? (Syntastic, Gitgutter, Gist, Gblame, ...)

**Comment by krompus** [comment]
Oh shit. `Gist` fails now too. I get

    Posting it to gist...
    Post failed: Continue

I'm not sure it's related, though. I don't have Syntastic/Gitgutter to test.

Then again, there's another similar command that works:

    command! -range=% PB silent execute <line1> . "," . <line2> . "w !curl -F 'c=@-' https://ptpb.pw/ | sed -n 's/^url: //p' | xclip -selection clipboard"

`:PB` don't give me no problem

I have assigned and tested the leader binds you mentioned in the readme. Same deal.

**Comment by kewah** [comment]
Sorry I just realised that the issue might not be in Vim, the command Stylefmt is actually executed that's why you get the error message `Error while executing stylefmt! no changes made`. (see https://github.com/kewah/vim-stylefmt/blob/c328a164c5ea65ae289da9b9d7eae61c67d12c0f/plugin/cssfmt.vim#L36)

Do you have stylefmt installed globally with npm? (`npm install -g stylefmt`)
If you try `stylefmt --version` in your terminal, what do you get?

**Comment by krompus** [comment]
Well, derp. I hadn't installed with npm. I should have reread the README, haha. Works fine now!

Was that added in the past few months? I seemed to remember cssfmt being a strict vim plugin, so I basically just s/css/Style in my .vimrc. :)

Thank you for putting up with my incompetence. Hopefully this thread helps another derp like me.

**Comment by kewah** [comment]
No worries ;) the change is pretty recent.

I'm glad we found a solution
