### ISSUE TITLE
Support formatting through `formatprg`

### ISSUE THREAD

**Issue by lkraav** [kewah/vim-stylefmt#6]
`autocmd FileType css,scss setlocal formatprg` would make sense to implement over separate `Stylefmt` commands. `gq` mnemonics for formatting across all filetypes is quick, thereby useful.

**Comment by kewah** [comment]
Sorry for the late response.
Nice, I didn't know formatprg before. I'm looking at http://vimcasts.org/episodes/using-external-filter-commands-to-reformat-html/ would it be possible to directly run `stylefmt` without having to use the plugin at all?

**Comment by lkraav** [comment]
Yes, I believe so. I have this right now as a workaround

.vimrc
`autocmd FileType css,less,scss setlocal formatprg=postcss\ -c\ /home/warmpress/postcss-vim-formatprg.json`

postcss-vim-formatprg.json
```json
{
    "parser": "postcss-safe-parser",  
    "postcss-sorting": {
        "sort-order": "alphabetical"                               
    },     
    "use": ["postcss-sorting"]
}
```

until `stylefmt` improves to not pushing its own default rules over `stylelint` configuration.

So this runs some really simple formatting rules right now using a simple CLI command. Looking forward to being able to use `stylefmt` instead here.

**Comment by kewah** [comment]
Interesting, thanks for the example!
FWIU there is not much that can be done on vim-stylefmt side. Therefore I'm closing the issue, feel free to reopen it if I got something wrong :)

**Comment by lkraav** [comment]
I was thinking perhaps a `README.md` documentation patch to illustrate a more optimal usage.

In theory... the plugin repo contents should maybe should just `README.md` :)

**Comment by kewah** [comment]
Sure thing, feel free to add a note int the readme to explain how to use formatprg.
I need to test it by myself to see how things work :)
